In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('C:\VS Code\Advertising/Advertising.csv',index_col=0)

In [3]:
df.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 7.8 KB


In [14]:
X = df.drop('sales', axis=1)
y = df['sales']
n = len(y)
X = np.append(np.ones((n,1)), X.values.reshape(n,3), axis = 1)
y = df['sales'].values.reshape(n,1)
par = np.zeros((4,1))


In [6]:
X

array([[  1. , 230.1,  37.8,  69.2],
       [  1. ,  44.5,  39.3,  45.1],
       [  1. ,  17.2,  45.9,  69.3],
       [  1. , 151.5,  41.3,  58.5],
       [  1. , 180.8,  10.8,  58.4],
       [  1. ,   8.7,  48.9,  75. ],
       [  1. ,  57.5,  32.8,  23.5],
       [  1. , 120.2,  19.6,  11.6],
       [  1. ,   8.6,   2.1,   1. ],
       [  1. , 199.8,   2.6,  21.2],
       [  1. ,  66.1,   5.8,  24.2],
       [  1. , 214.7,  24. ,   4. ],
       [  1. ,  23.8,  35.1,  65.9],
       [  1. ,  97.5,   7.6,   7.2],
       [  1. , 204.1,  32.9,  46. ],
       [  1. , 195.4,  47.7,  52.9],
       [  1. ,  67.8,  36.6, 114. ],
       [  1. , 281.4,  39.6,  55.8],
       [  1. ,  69.2,  20.5,  18.3],
       [  1. , 147.3,  23.9,  19.1],
       [  1. , 218.4,  27.7,  53.4],
       [  1. , 237.4,   5.1,  23.5],
       [  1. ,  13.2,  15.9,  49.6],
       [  1. , 228.3,  16.9,  26.2],
       [  1. ,  62.3,  12.6,  18.3],
       [  1. , 262.9,   3.5,  19.5],
       [  1. , 142.9,  29.3,  12.6],
 

In [7]:
def cost_function(X, y , par):
    y_pred = np.dot(X, par)
    error = (y_pred - y)**2
    cost = 1/(n)*np.sum(error)
    return cost

In [8]:
def grad_d(X,y, par, alpha, iterations):
    costs = []
    for i in range(iterations):
        y_pred = np.dot(X, par)
        der = np.dot (X.transpose(), (y_pred - y))/ n
        par -= alpha * der
        costs.append(cost_function(X,y, par))
    return par, costs

In [9]:
par, costs = grad_d(X,y, par, 0.00005, 500000)

In [10]:
par

array([[ 2.86254595e+00],
       [ 4.59731305e-02],
       [ 1.89405798e-01],
       [-5.73781627e-04]])

In [15]:
costs

[71.35866226812729,
 31.63186753172906,
 20.891196519617544,
 17.636388306647813,
 16.33899106226901,
 15.575638385003808,
 14.978195570399212,
 14.449909166082426,
 13.96393761929696,
 13.511559333899891,
 13.088849945366219,
 12.693247393027073,
 12.322659077545518,
 11.975223134384878,
 11.64923854017164,
 11.343139274495138,
 11.055480416715273,
 10.78492787492629,
 10.530249569231229,
 10.29030746907513,
 10.064050292992851,
 9.850506787051875,
 9.648779528690094,
 9.45803921294073,
 9.27751938296258,
 9.106511570163676,
 8.944360812012299,
 8.790461518139407,
 8.644253657631255,
 8.505219242522045,
 8.37287908444186,
 8.246789803168799,
 8.126541067488077,
 8.011753050286263,
 7.902074081215079,
 7.797178481556334,
 7.696764567115559,
 7.600552806074898,
 7.508284119752891,
 7.419718315156758,
 7.334632639077706,
 7.2528204442774244,
 7.174089959049494,
 7.0982631521176325,
 7.025174685458333,
 6.9546709482121525,
 6.886609165379871,
 6.8208565754902635,
 6.757289671878575,
 6.69

In [11]:

import statsmodels.api as sm
mod = sm.OLS(y, X)
res = mod.fit()
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Sat, 06 Jan 2024   Prob (F-statistic):           1.58e-96
Time:                        08:47:04   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.0

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)
print(model.coef_)
print(model.intercept_)

[[ 0.          0.04576465  0.18853002 -0.00103749]]
[2.93888937]
