In [27]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA, TruncatedSVD


In [6]:
A = np.matrix([[3, 4, 1], [1, 6, 2]])
A

matrix([[3, 4, 1],
        [1, 6, 2]])

In [9]:
df = pd.DataFrame(A,columns  = ['x1','x2','x3'])
df_std  = (df - df.mean()) / (df.std())
df_std

x1        x2        x3
0  0.707107 -0.707107 -0.707107
1 -0.707107  0.707107  0.707107

In [10]:
cov_mat = np.cov(df_std.T)
cov_mat

array([[ 1., -1., -1.],
       [-1.,  1.,  1.],
       [-1.,  1.,  1.]])

In [11]:
eigen_val, eigen_vectors = np.linalg.eig(cov_mat)

In [12]:
np.cov(np.array([3,4,1]),np.array([1,6,2])).sum()

14.333333333333334

In [20]:
A = np.matrix([[8,7,2,9],
               [1,3,6,3],
               [7,2,0,3],
               [10,3,1,1],
               [8,1,3,4]])

In [21]:
df = pd.DataFrame(A)
df_std  = (df - df.mean()) / (df.std())

In [23]:
#определяем метод главных компонент с двумя компонентами
pca = PCA(n_components=0.9)
#обучаем алгоритм на наших данных
principalComponents = pca.fit_transform(df_std)
principalComponents

array([[-1.61145254,  1.76368007,  0.01320928],
       [ 2.08441051,  1.01724955, -0.24417084],
       [-0.29568142, -0.95946326, -0.05272576],
       [-0.50390826, -1.24373821, -0.50808763],
       [ 0.3266317 , -0.57772816,  0.79177495]])

In [18]:
A = np.matrix([[8,7,2,9],
               [1,3,6,3],
               [7,2,0,3],
               [10,3,1,1],
               [8,1,3,4]])
 
df = pd.DataFrame(A)
df_std  = (df - df.mean()) / (df.std())
pca = PCA(n_components=0.9)
principalComponents = pca.fit_transform(df_std)

In [19]:
principalComponents

array([[-1.61145254,  1.76368007,  0.01320928],
       [ 2.08441051,  1.01724955, -0.24417084],
       [-0.29568142, -0.95946326, -0.05272576],
       [-0.50390826, -1.24373821, -0.50808763],
       [ 0.3266317 , -0.57772816,  0.79177495]])

In [26]:
A = np.matrix([[-1, 1, 0], [-1, -1, 1]])
np.dot(A, A.T)

matrix([[2, 0],
        [0, 3]])